"""empty message

Revision ID: 407d2436cd09
Revises: 91eba6b8f3ae
Create Date: 2023-02-23 14:54:03.158160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407d2436cd09'
down_revision = '91eba6b8f3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iduser', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['iduser'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('iduser')

    # ### end Alembic commands ###
