"""empty message

Revision ID: 44e2230997db
Revises: cdba42ced48b
Create Date: 2023-02-22 18:30:56.084781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e2230997db'
down_revision = 'cdba42ced48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('iduser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iduser', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.drop_table('favorites')
    # ### end Alembic commands ###
